EduView/urls.py
from django.contrib import admin
from django.urls import path, include

from django.urls import re_path
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("studentBase.urls")),
    path("api/", include("studentBase.api.urls")),
    re_path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
    re_path(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

studentBase/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.getRoutes),
    path("pdf_to_png", views.getPdfToPng),
]

studentBase/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("student/<int:id>/", views.profile, name="profile"),
    path("update-profile/<int:id>", views.update_profile, name="update-profile"),
    path("delete-student/<int:id>", views.delete_student, name="delete_student"),
    path("login/", views.user_login, name="login"),
    path("logout/", views.teacher_logout, name="logout"),
    path("register/", views.UserRegisterView.as_view(), name="register"),
    path("activate/<str:uid>/<str:token>", views.activate, name="activate"),
    path("settings/", views.settings, name="settings"),
    path("delete/", views.delete_user, name="delete_teacher"),
    path("approval/<str:pk_encoded>", views.teacher_approval, name="teacher_approval"),
    path('chat/',views.chat, name='chat_box'),
    path('get_recent_viewed_profiles/', views.get_recent_viewed_profiles, name='get_recent_viewed_profiles'),

]

studentBase/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError


class Profile(models.Model):
    Student_ID = models.IntegerField(unique=True)
    First_Name = models.CharField(max_length=50)
    Middle_Name = models.CharField(max_length=50, null=True, blank=True)
    Last_Name = models.CharField(max_length=50)
    Gender = models.CharField(max_length=25, null=True, blank=True)
    Grade = models.CharField(max_length=10, null=True, blank=True)
    Photo = models.CharField(null=True, blank=True, max_length=200)
    Schedule = models.CharField(null=True, blank=True, max_length=200)
    Social_Media = models.CharField(max_length=50, null=True, blank=True)
    Address = models.CharField(max_length=50, null=True, blank=True)
    Email = models.EmailField(null=True, blank=True)
    Contact_1 = models.CharField(max_length=12, null=True, blank=True)
    Contact_2 = models.CharField(max_length=12, null=True, blank=True)

    def __str__(self):
        return f"{self.First_Name} {self.Middle_Name} {self.Last_Name}".strip()


class User(AbstractUser):
    is_teacher = models.BooleanField("Teacher_status", default=False)
    is_student = models.BooleanField("Student_status", default=False)
    profile_pic = models.ImageField(default="default-avatar.jpg", upload_to="media/")
    is_email_verified = models.BooleanField("Email_status", default=False)
    student_id = models.IntegerField(unique=True, null=True, blank=True)

    def save(self, *args, **kwargs):
        if self.is_student and self.is_teacher:
            raise ValidationError("A user cannot be both a teacher and a student. ")
        if self.is_student and self.is_student is None:
            raise ValidationError("Student must have a id")
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.first_name} {self.last_name}".strip()


class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='sent_message',null=True)
    recipient = models.ForeignKey(User, on_delete=models.SET_NULL,related_name='received_message',null=True)
    body = models.TextField()
    create_on = models.DateTimeField(auto_now=True)


    class Meta:
        ordering =['-create_on']

    def __str__(self):
        return f'from {self.user} to {self.recipient}'

studentBase/api/views.py
import time
from rest_framework.decorators import api_view
from rest_framework.response import Response
from pdf2image import convert_from_path
import os
from django.http import HttpResponse
import shutil


@api_view(["GET"])
def getRoutes(request):
    routes = ["GET /api", "GET /api/pdf_to_png"]
    return Response(routes)


@api_view(["POST"])
def getPdfToPng(request):
    try:
        pdf_file = request.FILES["pdf_file"]
        temp_path = "static/temp/"
        with open(os.path.join(temp_path, str(pdf_file)), "wb+") as temp:
            for chunk in pdf_file.chunks():
                temp.write(chunk)

        images = convert_from_path(
            os.path.join(temp_path, str(pdf_file)),
            poppler_path="/opt/homebrew/Cellar/poppler/24.04.0/bin",
        )
        pdf_file = str(pdf_file)
        image_name = pdf_file[: len(list(pdf_file)) - 4]
        for i in range(len(images)):
            images[i].save(os.path.join(temp_path, str(image_name) + ".jpg"), "JPEG")

        image_path = os.path.join(temp_path, image_name + ".jpg")
        with open(image_path, "rb") as img:
            clearTemp()
            return HttpResponse(img.read(), content_type="image/jpeg")
    except Exception as e:
        print(e)
        clearTemp()
        return HttpResponse("An error occurred: " + str(e), status=500)


def clearTemp():
    temp = "static/temp"
    shutil.rmtree(temp)
    os.makedirs(temp, exist_ok=True)

studentBase/views.py
import os
from dotenv import load_dotenv
load_dotenv()
from .google_services.services import get_all_ids, get_all_students
from .google_services.update_gsheet import row_range
from django.db.models import Q
from django.shortcuts import render, redirect
from .models import Profile
from .forms import UpdateForm, RegisterForm, UpdateUserForm
from .google_services.update_gsheet import data_org
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .constants import SHEET_NAME
from django.contrib import messages
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from .tokens import token_generator
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.core.mail import send_mail
from .models import User, Message
from django.contrib.auth.decorators import user_passes_test
from django.views.generic import FormView
from django.http import JsonResponse


def user_login(request):
    if request.user.is_authenticated and request.user.is_teacher:
        return redirect("home")
    elif request.user.is_authenticated and request.user.is_student:
        return redirect('message_field')

    if request.method == "POST":
        username = request.POST.get("username").lower()
        password = request.POST.get("password")
        try:
            user = User.objects.get(username=username)
        except:
            user = None

        if user is not None and user.is_active and user.is_email_verified:
            if user is not None:
                user = authenticate(request, username=username, password=password)
                print(user)
                login(request, user)
                if user.is_teacher:
                    return redirect("home")
                else:
                    return redirect('message_field')

            else:
                messages.error(request, "Incorrect password")
        elif user is not None and (not user.is_active or not user.is_email_verified):
            messages.error(
                request,
                "Either your email is not verified or admin did not activated your account",
            )
        else:
            messages.error(request, "User not found.")
            return redirect("login")
    return render(
        request,
        "studentBase/login.html", {'DEMO_PASSWORD':os.getenv('DEMO_PASSWORD')}
    )


def send_email_verification(request, user):
    current_site = get_current_site(request)
    message = render_to_string(
        "studentBase/account_activation.html",
        {
            "domain": current_site,
            "token": token_generator.make_token(user),
            "uid": urlsafe_base64_encode(force_bytes(user.pk)),
            "user": user,
        },
    )
    subject = "Email verification for EduView account"
    send_mail(
        subject=subject,
        recipient_list=[user.email],
        message=message,
        from_email=os.environ.get("FROM_EMAIL"),
    )


# class base register view


class UserRegisterView(FormView):
    template_name = "studentBase/register.html"
    form_class = RegisterForm

    def form_valid(self, form):
        user = form.save(commit=False)
        user.email, user.username = user.email.lower(), user.username.lower()
        user.is_active = False
        if form.cleaned_data["User_role"] == "Teacher":
            user.is_teacher = True
        elif form.cleaned_data["User_role"] == "Student":
            user.is_student = True
            student_id = int(self.request.POST.get("student_id"))
            if Profile.objects.filter(Student_ID=student_id).exists():
                user.student_id = student_id
        user.save()
        try:
            send_email_verification(self.request, user)
            messages.success(
                self.request, "An verification email has been sent to your email"
            )
            return redirect("register")
        except:
            messages.error(
                self.request,
                "Something wrong with the email verification system. Please contact admin",
            )
            return redirect("register")
        return super().form_valid(form)

    def form_invalid(self, form):
        username = self.request.POST.get("username").lower()

        if (
                User.objects.filter(username=username).exists()
                and User.objects.get(username=username).is_email_verified == False
        ):
            user = User.objects.get(username=username)
            send_email_verification(self.request, user)
            messages.success(self.request, "Activation email sent to your email")
            return super().form_invalid(form)

        if User.objects.filter(username=username).exists():
            messages.error(
                self.request, "Username taken. Please try a different username."
            )
        else:
            messages.error(self.request, "An unknown error has occurred!")
        return super().form_invalid(form)

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect("home")
        return super().get(self, request, *args, **kwargs)


def activate(request, uid, token):
    try:
        pk = force_str(urlsafe_base64_decode(uid))
        user = User.objects.get(pk=pk)
    except:
        user = None

    if user is not None and user.is_teacher:

        if user.is_email_verified:
            message = "Email is already verified. Please wait for admin to approve your account."
            return render(request, "studentBase/messages.html", {"message": message})

        elif token_generator.check_token(user, token):
            user.is_email_verified = True
            user.save()
            message = "Your email has been successfully verified. Please wait for admin to approve your teacher account"
            current_site = get_current_site(request)
            encoded_pk = urlsafe_base64_encode(force_bytes(user.pk))
            approval_message = str(
                f"Approval request from {user.first_name} {user.last_name}: http://{current_site}/approval/{encoded_pk}"
            )
            try:
                send_mail(
                    subject=f"Approval request from {user.first_name} {user.last_name}",
                    message=approval_message,
                    from_email=os.environ.get("FROM_EMAIL"),
                    recipient_list=[os.environ.get("ADMIN_EMAIL")],
                )
            except:
                message = (
                    "Unable to send approval request to the admin. Please contact admin"
                )
        else:
            message = "The link is either invalid or expired. Please register again"

    elif user is not None and user.is_student:
        user.is_active = True
        user.is_email_verified = True
        user.save()
        messages.success(request, "Email successfully verified. Please login")
        return redirect("login")

    else:
        message = "User does not exist"

    context = {"message": message}
    return render(request, "studentBase/messages.html", context)


def teacher_approval(request, pk_encoded):
    try:
        pk = force_str(urlsafe_base64_decode(pk_encoded))
        user = User.objects.get(pk=pk)
    except:
        user = None
        messages.error(request, "User doesn't exist")
        return render(request, "studentBase/messages.html")
    if user != None and user.is_active == True:
        message = "This person's account is already approved"
        return render(request, "studentBase/messages.html", {"message": message})
    if request.method == "POST":
        admin_email = os.environ.get("FROM_EMAIL")
        if "approve" in request.POST:
            user.is_active = True
            user.save()
            send_mail(
                subject="EduView account approved",
                message=f"Admin approved your EduView account! Please login via http://{get_current_site(request)}/login",
                from_email=admin_email,
                recipient_list=[user.email],
            )
            return redirect("home")
        else:
            send_mail(
                subject="Admin did not approved your EduView account!",
                message=f"Sorry to inform you that the admin declined your account. "
                        f"Please contact admin at {admin_email} for more information.",
                from_email=admin_email,
                recipient_list=[user.email],
            )
            user.delete()
            return redirect("home")

    context = {"pending_user": user}
    return render(request, "studentBase/approval.html", context)


@login_required(login_url="login")
def teacher_logout(request):
    logout(request)
    return redirect("login")


def teacher(user):
    return user.is_teacher


@login_required(login_url="login")
@user_passes_test(teacher, login_url='login')
def home(request):
    student_search = request.GET.get("Student_ID")
    if student_search is None:
        student_search = ""
    else:
        student_search = student_search.lower()

    students = Profile.objects.filter(
        Q(First_Name__icontains=student_search)
        | Q(Student_ID__icontains=student_search)
        | Q(Last_Name__icontains=student_search)
        | Q(Middle_Name__icontains=student_search)
     )
    # viewed_profiles_list = request.session.get("viewed_profiles", [])
    # viewed_profiles = Profile.objects.filter(Student_ID__in=viewed_profiles_list)
    # viewed_profiles = sorted(
    #     viewed_profiles,
    #     key=lambda profile: viewed_profiles_list.index(profile.Student_ID),
    # )

    if request.user.is_student:
        user = request.user
        student_id = user.student_id

studentBase/templates/studentBase/approval.html
{% extends 'main.html' %}

{% block contain %}
<style>

.card {
  border-radius: 5px;
  display: flex;
  flex-direction: column;
  align-items: center;
  box-shadow: rgba(0,0, 0, 0.7);
  color: white;
}

.card__name {
  margin-top: 15px;
  font-size: 1.5em;
}

.card__image {
  height: 160px;
  width: 160px;
  border-radius: 50%;
  border: 5px solid #272133;
  margin-top: 20px;
  box-shadow: 0 10px 50px rgb(75, 230, 50);
}


.draw-border {
  box-shadow: inset 0 0 0 4px #58cdd1;
  color: #58afd1;
  -webkit-transition: color 0.25s 0.0833333333s;
  transition: color 0.25s 0.0833333333s;
  position: relative;
}

.draw-border::before,
.draw-border::after {
  border: 0 solid transparent;
  box-sizing: border-box;
  content: '';
  pointer-events: none;
  position: absolute;
  width: 0rem;
  height: 0;
  bottom: 0;
  right: 0;
}

.draw-border::before {
  border-bottom-width: 4px;
  border-left-width: 4px;
}

.draw-border::after {
  border-top-width: 4px;
  border-right-width: 4px;
}

.draw-border:hover {
  color: #ffe593;
}

.draw-border:hover::before,
.draw-border:hover::after {
  border-color: #1369e6;
  -webkit-transition: border-color 0s, width 0.25s, height 0.25s;
  transition: border-color 0s, width 0.25s, height 0.25s;
  width: 100%;
  height: 100%;
}

.draw-border:hover::before {
  -webkit-transition-delay: 0s, 0s, 0.25s;
  transition-delay: 0s, 0s, 0.25s;
}

.draw-border:hover::after {
  -webkit-transition-delay: 0s, 0.25s, 0s;
  transition-delay: 0s, 0.25s, 0s;
}

.btn {
  background: none;
  border: none;
  cursor: pointer;
  line-height: 1.5;
  font: 700 1.2rem 'Roboto Slab', sans-serif;
  padding: 0.75em 2em;
  letter-spacing: 0.05rem;
  margin: 1em;
  width: 13rem;
}

.btn:focus {
  outline: 2px dotted #55d7dc;
}


.social-icons {
  padding: 0;
  list-style: none;
  margin: 1em;
}

.social-icons li {
  display: inline-block;
  margin: 0.15em;
  position: relative;
  font-size: 1em;
}

.social-icons i {
  color: #fff;
  position: absolute;
  top: 0.95em;
  left: 0.96em;
  transition: all 265ms ease-out;
}

.social-icons a {
  display: inline-block;
}

.social-icons a:before {
  transform: scale(1);
  -ms-transform: scale(1);
  -webkit-transform: scale(1);
  content: " ";
  width: 45px;
  height: 45px;
  border-radius: 100%;
  display: block;
  background: linear-gradient(45deg, #16d9e8, #c648c8);
  transition: all 265ms ease-out;
}

.social-icons a:hover:before {
  transform: scale(0);
  transition: all 265ms ease-in;
}

.social-icons a:hover i {
  transform: scale(2.2);
  -ms-transform: scale(2.2);
  -webkit-transform: scale(2.2);
  color: #4e4848;
  background: -webkit-linear-gradient(45deg, #4a3f41, #514351);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  transition: all 265ms ease-in;
}

.grid-container {
  display: grid;
  grid-template-columns: 1fr 1fr;
  grid-gap: 20px;
  font-size: 1.2em;
}

</style>    
    
<div class="container">
  <div class="card">
    <img src="/media/default-avatar.jpg" alt="Person" class="card__image">
      <br>
          <p class="card__name">{{ pending_user.first_name}} {{ pending_user.last_name }}</p>
          <p class="card__name">{{ pending_user.email}}</p>
          <ul class="social-icons">
              <li><a ><i class="fa fa-instagram"></i></a></li>
              <li><a><i class="fa fa-twitter"></i></a></li>
              <li><a ><i class="fa fa-linkedin"></i></a></li>
              <li><a ><i class="fa fa-codepen"></i></a></li>
          </ul>
        <form method="POST">
            {% csrf_token %}
        <button class="btn draw-border" name="approve" type="submit">Approve</button>
        <button class="btn draw-border" name="decline" type="submit">Decline</button>
     </form> 

  </div>
</div>

{% endblock contain %}

studentBase/templates/studentBase/chat_box.html
{% load static %}

{% block contain %}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">
<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css'><link rel="stylesheet" href="{% static 'styles/style_chat_box.css' %}">

<style>
.avatar.avatar--medium img {
  width: 3.6rem;
  height: 3.6rem;
  border-radius: 50%;
}

.avatar.avatar--medium:after {
  width: 0.7rem;
  height: 0.7rem;
  bottom: 0px;
  right: -6px;
}

</style>
<body>
<!-- partial:index.partial.html -->
<div class="container clearfix">
    <div class="people-list" id="people-list">
      <div class="search">
        <input type="text" placeholder="search" />
        <i class="fa fa-search"></i>
      </div>
        
      <ul class="list">
        {% for teacher in teachers %}  
        <li class="clearfix">
            
        <div class="avatar avatar--medium">
            <img src="{{ teacher.profile_pic.url }}" alt=""/>
        </div>
          <div class="about">
            <div class="name">{{ teacher.first_name}} {{ teacher.last_name }}</div>
            <div class="status">
            </div>
          </div>
        </li>
          {% endfor %}
          
      </ul>
    </div>
    
    <div class="chat">
      <div class="chat-header clearfix">
        <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/195612/chat_avatar_01_green.jpg" alt="avatar" />
        
        <div class="chat-about">
          <div class="chat-with">Chat with Vincent Porter</div>
          <div class="chat-num-messages">already 1 902 messages</div>
        </div>
        <i class="fa fa-star"></i>
      </div> <!-- end chat-header -->
      
      <div class="chat-history">
        <ul>
          <li class="clearfix">
            <div class="message-data align-right">
              <span class="message-data-time" >10:10 AM, Today</span> &nbsp; &nbsp;
              <span class="message-data-name" >Olia</span> <i class="fa fa-circle me"></i>
              
            </div>
            <div class="message other-message float-right">
              Hi Vincent, how are you? How is the project coming along?
            </div>
          </li>
          
          <li>
            <div class="message-data">
              <span class="message-data-name"><i class="fa fa-circle online"></i> Vincent</span>
              <span class="message-data-time">10:12 AM, Today</span>
            </div>
            <div class="message my-message">
              Are we meeting today? Project has been already finished and I have results to show you.
            </div>
          </li>
            
          
        </ul>
        
      </div> <!-- end chat-history -->
      
      <div class="chat-message clearfix">
        <textarea name="message-to-send" id="message-to-send" placeholder ="Type your message" rows="3"></textarea>
                
        <i class="fa fa-file-o"></i> &nbsp;&nbsp;&nbsp;
        <i class="fa fa-file-image-o"></i>
        
        <button>Send</button>

      </div> <!-- end chat-message -->
      
    </div> <!-- end chat -->
    
  </div> <!-- end container -->

<script id="message-template" type="text/x-handlebars-template">
  <li class="clearfix">
    <div class="message-data align-right">
      <span class="message-data-time" >{{time}}, Today</span> &nbsp; &nbsp;
      <span class="message-data-name" >Olia</span> <i class="fa fa-circle me"></i>
    </div>
    <div class="message other-message float-right">
      {{messageOutput}}
    </div>
  </li>
</script>

<script id="message-response-template" type="text/x-handlebars-template">
  <li>
    <div class="message-data">
      <span class="message-data-name"><i class="fa fa-circle online"></i> Vincent</span>
      <span class="message-data-time">{{time}}, Today</span>
    </div>
    <div class="message my-message">
      {{response}}
    </div>
  </li>
</script>
<!-- partial -->
  <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.0/handlebars.min.js'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/list.js/1.1.1/list.min.js'></script><script  src="../../../static/styles/script_chat_box.js"></script>

</body>

{% endblock contain %}

studentBase/templates/studentBase/delete.html
{% extends 'main.html' %}

{% block contain %}
    <style>
        .flex-container {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
        }
        .alert-info {
            color: white;
            font-family: Arial, serif;
            font-size: 25px;

        }
        .confirm-delete {
            font-family: Arial, serif;
            background-color: #bc0b0b;
            color: white;
            border: none;
            padding: 8px 7px ;
            cursor: pointer;
            border-radius: 5px;
            transition: background-color 0.15s;

        }
        .confirm-delete:hover {
            background-color: #c36161;
        }
        .cancel-button {
            font-family: Arial, serif;
            background-color: #33bc33;
            text-decoration: none;
            color: white;
            padding: 6px 5px;
            border-radius: 5px;
            transition: background-color 0.15s;

        }
        .cancel-button:hover {
            background-color: #8ccc8c;
        }



    </style>
    <div class="flex-container">
        <p class="alert-info" role="alert">
            {% if user.username != None %}
            Are you sure you want to delete {{ user.username }}?
            {% else %}
            Are you sure you want to delete {{ user.Student_ID }}?
            {% endif %}
        </p>
        <form method="POST" action =''>
            {% csrf_token %}
            <button type="submit" class="confirm-delete">Confirm Delete</button>
            <a class="cancel-button" href="{% url 'home' %}">Cancel</a>
        </form>

    </div>
{% endblock contain %}

studentBase/templates/studentBase/delete_student.html
{% extends 'main.html' %}

{% block contain %}
    <div>
        <h1 class="text-center mb-4" style="color: #990000">Delete Student</h1>
        <div class="alert alert-danger" role="alert">
            Are you sure you want to delete the student with ID: {{ student.Student_ID }}?
        </div>
        <form method="POST" action =''>
            {% csrf_token %}
            <button type="submit" class="btn btn-danger" style="background-color: #990000">Confirm Delete</button>
            <a href="{% url 'home' %}" class="btn btn-secondary" style="background-color:#009926">Cancel</a>
            
        </form>
    

    </div>
{% endblock contain %}

studentBase/templates/studentBase/messages.html
{% extends 'main.html' %}

{% block contain %}
    <div style="display: flex; justify-content: center; align-items: center; height: 100vh;">
        {% for message in messages %}
            <p style="font-size: 2em;">{{ message }}</p>
        {% endfor %}
        <p style="font-size: 2em;">{{ message }}</p>
    </div>
{% endblock contain %}

studentBase/templates/studentBase/register.html
{% extends 'main.html' %}

{% block contain %}

    <style>
        .register-field-flex {
            display: flex;
            flex-direction: row;
            justify-content: center;
            padding-top: 50px;

        }

        .register-box {
            background-color: white;
            height: 500px;
            width: 300px;
            border-radius: 20px;
            box-shadow: inset 0px 0px 10px rgba(0, 0, 0, 0.5);
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            padding-right: 20px;
            padding-left: 20px;

        }

        .register-labels {
            display: grid;
            grid-template-columns: 1fr 1fr;
            font-family: Arial, serif;
            margin-bottom: 20px;
        }

        .register-text {
            font-family: Arial, serif;
            font-size: 20px;
            font-weight: bold;
        }

        .register-button-container {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }

        .register-button {
            background-color: #19e05f;
            border: none;
            border-radius: 10px;
            font-size: 15px;
            padding: 4px 7px;
            cursor: pointer;
        }

        .login-button {
            background-color: #00d0ff;
        }

    </style>

    <div class="register-field-flex">
        <div class="register-box">
            <p class="register-text">Register</p>
            <form class="form" action="" method="POST">
                {% csrf_token %}
                {% for field in form %}
                    <div class="register-labels">
                        <label for="room_name">{{ field.label }}:</label>
                        {{ field }}
                    </div>
                {% endfor %}

                {% if messages %}
                    <ul>
                        <li>
                            {% for message in messages %}
                                {{ message }}
                            {% endfor %}
                        </li>
                    </ul>
                {% endif %}

                {% if form.email.errors %}
                    {% for error in form.email.errors %}
                        {{ error }}
                    {% endfor %}
                {% endif %}

                <div id="studentIdField" class="register-labels">
                    <label for="id_student_id">Student ID:</label>
                    <input type="number" id="student_id" name="student_id">
                </div>

                <div class="register-button-container">

                    <button class="register-button" type="submit">
                        Register
                    </button>

                    <p>Already have an account?</p>
                    <button class="register-button login-button" onclick="location.href='{% url 'login' %}'">Login
                    </button>

                </div>


            </form>


        </div>

    </div>




    <script>
        const userRoleField = document.getElementById('id_User_role');
        const studentIdField = document.getElementById('studentIdField');
        studentIdField.style.display = 'none'
        const studentIdInput = document.getElementById('student_id');
        const showHideID = () => {
            const userRoleField = document.getElementById('id_User_role');
            console.log(userRoleField.value)
            if (userRoleField.value === 'Teacher') {
                studentIdField.style.display = 'none'
            } else {
                studentIdField.style.display = ''
            }

        }
        userRoleField.addEventListener('change', () => {
            showHideID()
        })

    </script>
{% endblock contain %}

studentBase/templates/studentBase/teacher_list_component.html
<style>
    .avatar-iframe {
        width: 50px;
        height: 50px;
        border-radius: 50%;
    }

    .activities {
        margin-left: 750px; /* Add this line */
    }
    
    .activities__box {
  margin: 1.5rem;
  padding: 1.5rem;
  border: 1px solid var(--color-dark-medium);
  border-radius: 30px;
}
    
</style>
<div class="activities">
  <div class="activities__header">
    <h2>Teacher lists</h2>
  </div>
  {% for teacher in teachers %}
  <div class="activities__box">
    <div class="activities__boxHeader roomListRoom__header">
      <a href="#" class="roomListRoom__author">
        <div class="avatar avatar--small">
                <img src="{{ teacher.profile_pic.url }}" alt="" class="avatar-iframe">
        </div>
      {{ teacher }}
        <p style="color: #e1f6fb">
        </p>
      </a>
    </div>

  </div>
  {% endfor %}
</div>